### PR TITLE
refactor: removing the configuration as a pointer

### PR DESCRIPTION
**Pull request by shairozan**
Closed the previous pull request. This branch removes the configuration as pointer altogether.

### CODE REVIEW

**Comment by shairozan** [comment]
All tests were previously passing and I've run it manually to confirm that it's resulting in the same behavior the previous branch did. Just different approach. Going to have Seth test it on Monday

**Comment by shairozan** [comment]
```go
if l.Nonmem.Configuration.NMQual {

		//Set parallelism to true
		l.Nonmem.Configuration.Parallel = true
		//TODO: What about the other parallel components?

		//If we can locate the key
		if selected, ok := l.Nonmem.Configuration.Nonmem[l.Nonmem.Configuration.NMVersion]; ok {
			//Is it not set to nmqual?
			if !selected.Nmqual {
				RecordConcurrentError(l.Nonmem.FileName, "Invalid nonmem / nmqual configuration", errors.New("NMQual was selected, but the selected nmversion does not support nmqual"), channels, l.Cancel)
				return
			}
		}
	}
```

Had me slightly concerned as it was the only place that we reached into the configuration to change a value from the execution perspective. I have verified, however, that both the generated Babylon yaml file and the JSON file both contain a `parallel` value of true after execution.

**Comment by dpastoor** [comment]
@shairozan Good to merge and tag so can use this in a build?

**Comment by shairozan** [comment]
Yeah it's good. Was waiting for Seth to update the issue confirming it worked. Been working on testing for Babylon stuff. I'll go ahead and merge into dev and create a new release

**Comment by shairozan** [comment]
@dpastoor v2.1.1-rc1 is available now.

**Pull request merged**
